"""Move database. Each move is a dict describing its battle effect."""

# category: "Physical", "Special", "Status"
# status effects applied via 'status': "brn"/"par"/"psn"/"slp"/"frz"
# 'stat_changes': dict of {target: 'self'/'target', stat: stages}
# 'priority': turn-order priority bracket (default 0)
# 'flinch_chance', 'secondary_status_chance' etc. simplified below via 'effect_chance'

MOVES = {
    "Tackle":       dict(type="Normal", category="Physical", power=40, accuracy=100, pp=35),
    "Scratch":      dict(type="Normal", category="Physical", power=40, accuracy=100, pp=35),
    "Ember":        dict(type="Fire", category="Special", power=40, accuracy=100, pp=25,
                          status="brn", effect_chance=10),
    "Flamethrower": dict(type="Fire", category="Special", power=90, accuracy=100, pp=15,
                          status="brn", effect_chance=10),
    "Fire Blast":   dict(type="Fire", category="Special", power=110, accuracy=85, pp=5,
                          status="brn", effect_chance=10),
    "Water Gun":    dict(type="Water", category="Special", power=40, accuracy=100, pp=25),
    "Surf":         dict(type="Water", category="Special", power=90, accuracy=100, pp=15),
    "Hydro Pump":   dict(type="Water", category="Special", power=110, accuracy=80, pp=5),
    "Vine Whip":    dict(type="Grass", category="Physical", power=45, accuracy=100, pp=25),
    "Razor Leaf":   dict(type="Grass", category="Physical", power=55, accuracy=95, pp=25,
                          high_crit=True),
    "Solar Beam":   dict(type="Grass", category="Special", power=120, accuracy=100, pp=10),
    "Thunder Shock":dict(type="Electric", category="Special", power=40, accuracy=100, pp=30,
                          status="par", effect_chance=10),
    "Thunderbolt":  dict(type="Electric", category="Special", power=90, accuracy=100, pp=15,
                          status="par", effect_chance=10),
    "Thunder":      dict(type="Electric", category="Special", power=110, accuracy=70, pp=10,
                          status="par", effect_chance=30),
    "Quick Attack": dict(type="Normal", category="Physical", power=40, accuracy=100, pp=30,
                          priority=1),
    "Ice Beam":     dict(type="Ice", category="Special", power=90, accuracy=100, pp=10,
                          status="frz", effect_chance=10),
    "Blizzard":     dict(type="Ice", category="Special", power=110, accuracy=70, pp=5,
                          status="frz", effect_chance=10),
    "Rock Slide":   dict(type="Rock", category="Physical", power=75, accuracy=90, pp=10),
    "Earthquake":   dict(type="Ground", category="Physical", power=100, accuracy=100, pp=10),
    "Dig":          dict(type="Ground", category="Physical", power=80, accuracy=100, pp=10),
    "Gust":         dict(type="Flying", category="Special", power=40, accuracy=100, pp=35),
    "Wing Attack":  dict(type="Flying", category="Physical", power=60, accuracy=100, pp=35),
    "Air Slash":    dict(type="Flying", category="Special", power=75, accuracy=95, pp=15),
    "Confusion":    dict(type="Psychic", category="Special", power=50, accuracy=100, pp=25),
    "Psychic":      dict(type="Psychic", category="Special", power=90, accuracy=100, pp=10,
                          stat_changes=[("target", "spd", -1)], effect_chance=10),
    "Bug Bite":     dict(type="Bug", category="Physical", power=60, accuracy=100, pp=20),
    "X-Scissor":    dict(type="Bug", category="Physical", power=80, accuracy=100, pp=15),
    "Poison Sting": dict(type="Poison", category="Physical", power=15, accuracy=100, pp=35,
                          status="psn", effect_chance=30),
    "Sludge Bomb":  dict(type="Poison", category="Special", power=90, accuracy=100, pp=10,
                          status="psn", effect_chance=30),
    "Shadow Ball":  dict(type="Ghost", category="Special", power=80, accuracy=100, pp=15,
                          stat_changes=[("target", "spd", -1)], effect_chance=20),
    "Lick":         dict(type="Ghost", category="Physical", power=30, accuracy=100, pp=30,
                          status="par", effect_chance=30),
    "Bite":         dict(type="Dark", category="Physical", power=60, accuracy=100, pp=25),
    "Crunch":       dict(type="Dark", category="Physical", power=80, accuracy=100, pp=15),
    "Dragon Claw":  dict(type="Dragon", category="Physical", power=80, accuracy=100, pp=15),
    "Dragon Breath":dict(type="Dragon", category="Special", power=60, accuracy=100, pp=20,
                          status="par", effect_chance=30),
    "Iron Tail":    dict(type="Steel", category="Physical", power=100, accuracy=75, pp=15),
    "Iron Head":    dict(type="Steel", category="Physical", power=80, accuracy=100, pp=15),
    "Moonblast":    dict(type="Fairy", category="Special", power=95, accuracy=100, pp=15,
                          stat_changes=[("target", "spa", -1)], effect_chance=30),
    "Dazzling Gleam": dict(type="Fairy", category="Special", power=80, accuracy=100, pp=10),
    "Close Combat": dict(type="Fighting", category="Physical", power=120, accuracy=100, pp=5,
                          stat_changes=[("self", "def", -1), ("self", "spd", -1)]),
    "Karate Chop":  dict(type="Fighting", category="Physical", power=50, accuracy=100, pp=25,
                          high_crit=True),
    "Body Slam":    dict(type="Normal", category="Physical", power=85, accuracy=100, pp=15,
                          status="par", effect_chance=30),
    "Hyper Beam":   dict(type="Normal", category="Special", power=150, accuracy=90, pp=5,
                          recharge=True),
    "Swords Dance": dict(type="Normal", category="Status", power=0, accuracy=100, pp=20,
                          stat_changes=[("self", "atk", 2)]),
    "Growl":        dict(type="Normal", category="Status", power=0, accuracy=100, pp=40,
                          stat_changes=[("target", "atk", -1)]),
    "Agility":      dict(type="Psychic", category="Status", power=0, accuracy=100, pp=30,
                          stat_changes=[("self", "spe", 2)]),
    "Recover":      dict(type="Normal", category="Status", power=0, accuracy=100, pp=10,
                          heal=0.5),
    "Toxic":        dict(type="Poison", category="Status", power=0, accuracy=90, pp=10,
                          status="tox", effect_chance=100),
    "Will-O-Wisp":  dict(type="Fire", category="Status", power=0, accuracy=85, pp=15,
                          status="brn", effect_chance=100),
    "Thunder Wave": dict(type="Electric", category="Status", power=0, accuracy=90, pp=20,
                          status="par", effect_chance=100),
    "Stealth Rock": dict(type="Rock", category="Status", power=0, accuracy=100, pp=20,
                          hazard="stealth_rock"),
}


def get_move(name):
    data = dict(MOVES[name])
    data["name"] = name
    data["max_pp"] = data["pp"]
    return data
